ch?=4
xbar?=true
hbm: hbm.tcl
	qsys-script --cmd="set hbm_channels $(ch); set en_xbar $(xbar)" --script=hbm.tcl
clean:
	rm -fr *qpf *qsf *qsys *qsys.legacy .qsys_edit/ hbm_ss/ ip/ *~ qdb/ dni/ board.info
